### ISSUE TITLE
revise/add tests for FITS images with multiple HDUs

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#175]
cf https://github.com/CARTAvis/carta-backend/pull/672

**Comment by zarda** [comment]
Since the ICD 19 updated the file info related message protobuf, we do need to update the corresponding tests.

- [ ] FILEINFO
- [ ] FILEINFO-EXCEPTION
- [ ] FILEINFO-FITS
- [ ] FILEINFO-CASA
- [ ] FILEINFO-HDF5
- [ ] FILEINFO-MIRIAD

Refer to CARTA.FileInfoResponse.file_info_extended, the type of which is changed from FileInfoExtended to map<string, FileInfoExtended>.

**Comment by zarda** [comment]
Integrated to the branch "/bump_icd_version19" with the #179.
