### ISSUE TITLE
preparing a test for the simple_omp backend branch

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#83]
Per Rob's request, we need a test to do some heavy jobs for one session and one backend. The design document is at 
https://docs.google.com/document/d/1p-y5cXXO1f9zh9BPfnX0EflHeCV_wX-17dTbYYZNnQc/edit

Test images: https://drive.google.com/open?id=13waJwNJoVRmZY1LsqEyS9KUPsaRJE8XB

related to #81 

- [x] test design
- [x] implementation
- [ ] verification

**Comment by acdo2002** [comment]
Hi Rob @robsimmonds ,
KS assigned this test implementation to me. 
The codes and running results are summarized in #81  

Please check them and please let me know if there is any question.
**For running individual large-size image:**
S255_IR_sci.spw29.cube.I.pbcor.fits (28.3 GB) & IRAS_17150-3224_sci.spw27.cube.I.manual.image.pbcor.fits (60.2 GB) are more stable then GV_Tau_sci.spw0.cube.I.manual.image.pbcor.fits (70.6 GB). 
I failed few times with running the largest image (see the deleted paragraph).

***For running three large-size images continuously*
Because I just start to understand animation playback, I finished Step1-10 first, it runs well. 
However when I add Step11(animation playback), backend server becomes very unstable. Sometime can pass the tests and sometime cannot. The successful testing result is shown in Final Test.
I try different step combinations (Test1 to Test4) to make sure my jest-test code is OK. If I blocked heavy steps (e.g. step 5, 7, 8, 9), the successful rate for running step11 may increase.
