### ISSUE TITLE
preparing a test for contour generation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#84]
need a test for SET_CONTOUR_PARAMETERS and CONTOUR_IMAGE_DATA

- [x] test design
- [ ] implementation
- [ ] verification

**Comment by acdo2002** [comment]
Te test design document is in [here](https://docs.google.com/document/d/1lU_Y5OyB7lqdZ4q2_LjnEVeTIXJj8yKl7SdsMK2lrhc/edit)

I am going to do the implementation now. Because ICD update (for example "ADD_REQUIRED_TILES"), the test content may change. I decide to do the implementation by myself (implementation verify can be done by others) then I will know whether the test design is ok or not.

**Comment by zarda** [comment]
Re-open as the issue #104
