### ISSUE TITLE
add test "CLOSE_FILE"

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#89]
Now CARTA supports "close file". ICD test is needed.

**Comment by zarda** [comment]
Does the test for this function need a new standalone testing or just be in an existent testing, like to append a this test to OPEN_IMAGE_APPEND.test.ts ?

**Comment by kswang1029** [comment]
We need a careful new design as close_file can happen in various scenarios

**Comment by zarda** [comment]
This ICD command has no return message so we need a different way to test whether it acts normally. For example, one solution is to exame if the backend is still active, e.g. connect.redayState == Connecting . 
If we send another request, the backend may resume a NEW session.

**Comment by kswang1029** [comment]
you can request stats from that closed image after the image is closed and check the responses of the backend. Should not crash and probably provide ERROR_DATA.

**Comment by acdo2002** [comment]
If we close the image, in principle there is no any additional message returned from the backend. Then we can set the time interval to make sure there is NO returned message as well as the connection.readyState == Connecting.

**Comment by kswang1029** [comment]
@acdo2002 it is more than that to be tested. We will need to check if the backend responds properly if a request to that closed image is made. 

Also need to check if other stream requests are still functional. For example, if there are three data streams before closing an image, after closing the rest two should be still functional.

**Comment by acdo2002** [comment]
The designed doc is [here](https://docs.google.com/document/d/1Md4_nMUKwdgd7rZvB7rF411ZjiqNlDoYBOHgUjUJmZU/edit?usp=sharing)

Three Tests, the first two are based on the UI behavior. 
The last one is the error test which cannot produced by the UI.

CLOSE_FILE_SINGLE: Testing close_file with single file. (simple behavior: open one file and then close it)
CLOSE_FILE_MULTI_FILES: Testing close_file with multiple files.
(case 1: open three files, close 3->2->1)
(case 2: open three files, close 1 & 2 together, then close 3)
(case 3: open three files and close them all together)
CLOSE_FILE_ERROR: Testing the backend should has NO response if requesting a closed file related message
(open two files, close 1 and request message of 1)

I used two methods to confirm the close_file is working:
(1) no additional message returned from the backend
(2) request one simple ICD message(e.g. open folder), then the backend should have reaction, in order to confirmed that the backend is still alive.

**Comment by kswang1029** [comment]
@acdo2002 I put some suggestions in the doc, especially for the case of data streaming. Please have a look.

**Comment by acdo2002** [comment]
Progress Report
CLOSE_FILE_SINGLE - [x] Designed - [x] Implementation
CLOSE_FILE_MULTI_FILES - [x] Designed - [ ] Implementation
CLOSE_FILE_ERROR - [x] Designed - [ ] Implementation
CLOSE_FILE_STREAM - [ ] Designed - [ ] Implementation
