### ISSUE TITLE
revise animator tests with the new tiled animation approach

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#90]
Once tiled animation is merged, we need to revise all animator related tests.

**Comment by kswang1029** [comment]
now tiled animation is in place. we need to revise animator related tests accordingly.

**Comment by acdo2002** [comment]
Here I show the jest-test code results from two different networks:
(1) Inside IAA (Ubuntu):
 PASS  src/test/ANIMATOR-PLAYBACK2.test.ts (8.376s)
  ANIMATOR_PLAYBACK test: Testing animation playback
    ✓ (Step 0) Connection open? |  (1ms)
    ✓ close file
    Go to "set_QA" folder
      (Step 1) Initialization: the open image
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 3000 ms (20ms)
        ✓ return RASTER_TILE_DATA(Stream) and check total length  (7ms)
      (Step 2):Play some channels forwardly
        ✓ Image should return one after one and the last channel is correct: (1933ms)
        ✓ Received image channels should be in sequence (19ms)
      (Step 3) Play some channels backwardly with looping
        ✓ Image should return one after one (2455ms)
        ✓ Received image channels should be in sequence (6ms)
      (Step 4 )Play some channels until stop
        ✓ Image should return one after one (1178ms)
        ✓ Last image on channel should receive after stop and should be between 10 and 12 (1ms)
      (Step 5) Play images round-trip
        ✓ Image should return one after one (1683ms)
        ✓ Received image channels should be in sequence and then reverse: (15ms)
      (Step 6) Play all images backwardly using method1
        ✓ Image should return one after one (276ms)
        ✓ Received image channels should be in sequence (7ms)
      (Step 6) Play all images backwardly using method2
        ✓ Image should return one after one (352ms)
        ✓ Received image channels should be in sequence (22ms)
      (Step 7) Blink images between 3 and 10
        ✓ Image should return one after one (299ms)
        ✓ Received image channels should be in sequence (10ms)

Test Suites: 1 passed, 1 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        8.386s

(2) Outside IAA (Mac): 
 PASS  src/test/ANIMATOR-PLAYBACK2.test.ts (22.024s)
  ANIMATOR_PLAYBACK test: Testing animation playback
    ✓ (Step 0) Connection open? |  (3ms)
    ✓ close file
    Go to "set_QA" folder
      (Step 1) Initialization: the open image
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 3000 ms (74ms)
        ✓ return RASTER_TILE_DATA(Stream) and check total length  (409ms)
      (Step 2):Play some channels forwardly
        ✓ Image should return one after one and the last channel is correct: (2085ms)
        ✓ Received image channels should be in sequence (36ms)
      (Step 3) Play some channels backwardly with looping
        ✓ Image should return one after one (4519ms)
        ✓ Received image channels should be in sequence (39ms)
      (Step 4 )Play some channels until stop
        ✓ Image should return one after one (2264ms)
        ✓ Last image on channel should receive after stop and should be between 10 and 12 (1ms)
      (Step 5) Play images round-trip
        ✓ Image should return one after one (5365ms)
        ✓ Received image channels should be in sequence and then reverse: (5ms)
      (Step 6) Play all images backwardly using method1
        ✓ Image should return one after one (846ms)
        ✓ Received image channels should be in sequence (5ms)
      (Step 6) Play all images backwardly using method2
        ✓ Image should return one after one (909ms)
        ✓ Received image channels should be in sequence (5ms)
      (Step 7) Blink images between 3 and 10
        ✓ Image should return one after one (979ms)
        ✓ Received image channels should be in sequence (6ms)

Test Suites: 1 passed, 1 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        22.719s

The test.ts jest-code continuously runs the animation-related messages. Although I have assigned different animation_id for each individual test, the missing tile may happened if the backend was busy. If the test.ts code passes, the backend terminal shows "No remaining sessions.", which I guess it may suggest everything goes right, otherwise the backend will show "X remaining sessions", then broken. 

Related word documentation will show up later.
